export const FETCH_SALES_REQUEST = 'FETCH_SALES_REQUEST'
export const FETCH_SALES_SUCCESS = 'FETCH_SALES_SUCCESS'
export const FETCH_SALES_FAILURE = 'FETCH_SALES_FAILURE'
export const FETCH_SALES_SELECTED = 'FETCH_SALES_SELECTED'
